/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
          // Menambahkan KeyListener untuk konversi otomatis
        inputField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                // Memanggil metode konversi setiap kali ada perubahan input
                convertTemperature();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        convertFromRadioButton = new javax.swing.JRadioButton();
        convertToRadioButton = new javax.swing.JRadioButton();
        fromScaleComboBox = new javax.swing.JComboBox<>();
        toScaleComboBox = new javax.swing.JComboBox<>();
        convertButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        inputField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APLIKASI KONVERSI SUHU ");

        jLabel2.setText("Masukkan Suhu");

        buttonGroup1.add(convertFromRadioButton);
        convertFromRadioButton.setSelected(true);
        convertFromRadioButton.setText("DARI");

        buttonGroup1.add(convertToRadioButton);
        convertToRadioButton.setText("KE");

        fromScaleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Reamur", "Kelvin" }));
        fromScaleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromScaleComboBoxActionPerformed(evt);
            }
        });

        toScaleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Reamur", "Kelvin", "Celsius" }));
        toScaleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toScaleComboBoxActionPerformed(evt);
            }
        });

        convertButton.setText("Konversi");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        resultLabel.setText("Hasil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(convertFromRadioButton)
                            .addComponent(jLabel2)
                            .addComponent(convertToRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputField)
                            .addComponent(fromScaleComboBox, 0, 104, Short.MAX_VALUE)
                            .addComponent(toScaleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultLabel)
                .addGap(169, 169, 169))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertFromRadioButton)
                    .addComponent(fromScaleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertToRadioButton)
                    .addComponent(toScaleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(convertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromScaleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromScaleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromScaleComboBoxActionPerformed

    private void toScaleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toScaleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toScaleComboBoxActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed

        convertTemperature(); // Memanggil metode konversi ketika tombol ditekan
        // TODO add your handling code here:
    }//GEN-LAST:event_convertButtonActionPerformed
  private void convertTemperature() {
        try {
            double inputTemperature = Double.parseDouble(inputField.getText());
            double result = 0;

            String fromScale = fromScaleComboBox.getSelectedItem().toString();
            String toScale = toScaleComboBox.getSelectedItem().toString();

            if (convertFromRadioButton.isSelected()) {
                // Konversi dari
                result = convertFromScale(inputTemperature, fromScale, toScale);
            } else if (convertToRadioButton.isSelected()) {
                // Konversi ke
                result = convertFromScale(inputTemperature, toScale, fromScale);
            }

            resultLabel.setText("Hasil: " + result + " " + toScale);
        } catch (NumberFormatException e) {
            resultLabel.setText("Input tidak valid!");
        }
    }

    private double convertFromScale(double temperature, String from, String to) {
        // Konversi suhu
        if (from.equals("Celsius")) {
            if (to.equals("Fahrenheit")) return (temperature * 9/5) + 32;
            if (to.equals("Reamur")) return temperature * 4/5;
            if (to.equals("Kelvin")) return temperature + 273.15;
        } else if (from.equals("Fahrenheit")) {
            if (to.equals("Celsius")) return (temperature - 32) * 5/9;
            if (to.equals("Reamur")) return (temperature - 32) * 4/9;
            if (to.equals("Kelvin")) return (temperature - 32) * 5/9 + 273.15;
        } else if (from.equals("Reamur")) {
            if (to.equals("Celsius")) return temperature * 5/4;
            if (to.equals("Fahrenheit")) return (temperature * 9/4) + 32;
            if (to.equals("Kelvin")) return (temperature * 5/4) + 273.15;
        } else if (from.equals("Kelvin")) {
            if (to.equals("Celsius")) return temperature - 273.15;
            if (to.equals("Fahrenheit")) return (temperature - 273.15) * 9/5 + 32;
            if (to.equals("Reamur")) return (temperature - 273.15) * 4/5;
        }
        return temperature; // Jika tidak ada konversi, kembalikan nilai asli
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton convertButton;
    private javax.swing.JRadioButton convertFromRadioButton;
    private javax.swing.JRadioButton convertToRadioButton;
    private javax.swing.JComboBox<String> fromScaleComboBox;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JComboBox<String> toScaleComboBox;
    // End of variables declaration//GEN-END:variables
}
